version: "3.9"

networks:
  pollite-network:

services:
  backend:
    image: pollite-backend
    container_name: backend
    build:
      context: ./backend
    ports:
      - "9000:8080"
    depends_on:
      - db-pollite
    networks:
      - pollite-network
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 3
        window: 60s

  frontend:
    image: pollite-frontend
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - pollite-network

  db-pollite:
    build: ./db
    ports:
      - "3309:3306"
    environment:
      MYSQL_DATABASE: pollite
      MYSQL_ROOT_PASSWORD: password
#      MYSQL_USER: pollite
#      MYSQL_PASSWORD: password
    networks:
      - pollite-network

#  mysqldb:
#    image: "mysql:8.0"
#    restart: always
#    ports:
#      - "3309:3306"
#    environment:
#      MYSQL_DATABASE: pollite
#      MYSQL_USER: pollite
#      MYSQL_PASSWORD: password
#      MYSQL_ROOT_PASSWORD: password
#    networks:
#    - pollite-network